name: friday

on:
  schedule:
    - cron: '0 5 * * 5'
  workflow_dispatch:
    inputs:
      env_vars:
        description: 'space-separated env vars, e.g. "DEBUG=1"'
        required: false
        default: ''
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - env:
          S_CI: ${{ secrets.S_CI }}
          S_CS: ${{ secrets.S_CS }}
          S_RT: ${{ secrets.S_RT }}
          S_PI: ${{ secrets.S_PI }}
          PYTHONUNBUFFERED: 1
        run: ${{ inputs.env_vars }} DATE=$(date -d "last saturday" +%Y-%m-%d) ./friday.py
